routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('pages.home');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::prefix('transaction')->group(function () {
        Route::get('/', [TransactionController::class, 'index'])->name('transaction.index');
        Route::get('/create', [TransactionController::class, 'create'])->name('transaction.create');
        Route::post('/', [TransactionController::class, 'store'])->name('transaction.store');
    });
});

require __DIR__.'/auth.php';

app/Models/Transaction.php
<?php

namespace App\Models;

use App\Traits\Modifier;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Transaction extends Model
{
    use HasFactory, Modifier, SoftDeletes;

    protected $fillable = [
        'type',
        'amount',
        'code',
        'note',
        'evidence',
    ];

    protected function createdAt(): Attribute
    {
        return Attribute::make(
            get: fn (string $value) => Carbon::parse($value)->format('d-m-Y H:i:s'),
        );
    }

    protected function amount(): Attribute
    {
        return Attribute::make(
            get: fn (string $value) => number_format($value, 0, ',', '.'),
        );
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

abstract class Controller
{
    //
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfileUpdateRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\View\View;

class ProfileController extends Controller
{
    /**
     * Display the user's profile form.
     */
    public function edit(Request $request): View
    {
        return view('profile.edit', [
            'user' => $request->user(),
        ]);
    }

    /**
     * Update the user's profile information.
     */
    public function update(ProfileUpdateRequest $request): RedirectResponse
    {
        $request->user()->fill($request->validated());

        if ($request->user()->isDirty('email')) {
            $request->user()->email_verified_at = null;
        }

        $request->user()->save();

        return Redirect::route('profile.edit')->with('status', 'profile-updated');
    }

    /**
     * Delete the user's account.
     */
    public function destroy(Request $request): RedirectResponse
    {
        $request->validateWithBag('userDeletion', [
            'password' => ['required', 'current_password'],
        ]);

        $user = $request->user();

        Auth::logout();

        $user->delete();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return Redirect::to('/');
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TransactionRequest;
use App\Models\Transaction;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;
use Yajra\DataTables\DataTables;

class TransactionController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $model = Transaction::where('created_by', Auth::user()->id);
            return DataTables::of($model)
                ->addIndexColumn()
                ->escapeColumns([])
                ->make(true); 
        }
        $user = User::find(Auth::user()->id);
        $data = [
            'user' => $user
        ];
        return view('pages.transaction.index', $data);
    }

    public function create()
    {
        $user = User::find(Auth::user()->id);
        $data = [
            'user' => $user
        ];
        return view('pages.transaction.create', $data);
    }

    public function store(TransactionRequest $request)
    {
        $payload = $request->validationData();
        $payload['code'] = 'TRX' . time();
        DB::beginTransaction();
        try {
            $model = Transaction::create($payload);

            if ($request->hasFile('evidence')) {
                $fileName = 'evidence_' . $model->id . '.' . $request->file('evidence')->extension();
                Storage::delete($fileName);
                Storage::putFileAs(
                    'evidence',
                    $request->file('evidence'),
                    $fileName
                );

                $model->evidence = 'evidence/' . $fileName;
                $model->save();
            }

            if ($payload['type'] == 'top_up') {
                $user = User::find(Auth::user()->id);
                $user->balance += $payload['amount'];
                $user->save();
            } elseif ($payload['type'] == 'transaksi') {
                $user = User::find(Auth::user()->id);
                if ($user->balance < $payload['amount']) {
                    throw new \Exception('Insufficient balance');
                }
                $user->balance -= $payload['amount'];
                $user->save();
            }
        } catch (\Exception $e) {
            DB::rollback();

            return Redirect::back()->with('error', $e->getMessage());
        }

        DB::commit();
        return Redirect::back()->with('success', 'Transaction created successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/AuthLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AuthLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts._auth');
    }
}

app/View/Components/DefaultLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class DefaultLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts._default');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    {{ __("You're logged in!") }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/_auth.blade.php
@extends('layouts.master-auth')

@section('content')

<div class="d-flex flex-column flex-root" id="kt_app_root">
	<!--begin::Authentication - Sign-in -->
	<div class="d-flex flex-column flex-lg-row flex-column-fluid">
		<!--begin::Logo-->
		<a href="../../demo38/dist/index.html" class="d-block d-lg-none mx-auto py-20">
			<img alt="Logo" src="assets/media/logos/default.svg" class="theme-light-show h-25px" />
			<img alt="Logo" src="assets/media/logos/default-dark.svg" class="theme-dark-show h-25px" />
		</a>
		<!--end::Logo-->
		<!--begin::Aside-->
		<div class="d-flex flex-column flex-column-fluid flex-center w-lg-50 p-10">
			<!--begin::Wrapper-->
			{{ $slot }}
			<!--end::Wrapper-->
		</div>
		<!--end::Aside-->
		<!--begin::Body-->
		<div class="d-none d-lg-flex flex-lg-row-fluid w-50 bgi-size-cover bgi-position-y-center bgi-position-x-start bgi-no-repeat" style="background-image: url(assets/media/auth/bg11.png)"></div>
		<!--begin::Body-->
	</div>
	<!--end::Authentication - Sign-in-->
</div>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            @isset($header)
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endisset

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/pages/transaction/create.blade.php
<x-default-layout>
    <div class="d-flex flex-column flex-column-fluid">
        <!--begin::Toolbar-->
        <div id="kt_app_toolbar" class="app-toolbar pt-7 pt-lg-10">
            <!--begin::Toolbar container-->
            <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex align-items-stretch">
                <!--begin::Toolbar wrapper-->
                <div class="app-toolbar-wrapper d-flex flex-stack flex-wrap gap-4 w-100">
                    <!--begin::Page title-->
                    <div class="page-title d-flex flex-column justify-content-center gap-1 me-3">
                        <!--begin::Title-->
                        <h1 class="page-heading d-flex flex-column justify-content-center text-dark fw-bold fs-3 m-0">Create Transaction</h1>
                        <!--end::Title-->
                    </div>
                    <!--end::Page title-->
                </div>
                <!--end::Toolbar wrapper-->
            </div>
            <!--end::Toolbar container-->
        </div>
        <!--end::Toolbar-->
        <!--begin::Content-->
        <div id="kt_app_content" class="app-content flex-column-fluid">
            <!--begin::Content container-->
            <div id="kt_app_content_container" class="app-container container-fluid">
                <!--begin::Layout-->
                <div class="d-flex flex-column flex-lg-row">
                    <!--begin::Content-->
                    <div class="flex-lg-row-fluid mb-10 mb-lg-0 me-lg-7 me-xl-10">
                        <!--begin::Card-->
                        <div class="card">
                            <!--begin::Card body-->
                            <div class="card-body p-12">
                                <!--begin::Form-->
                                @if (session()->has('success'))
                                <!--begin::Alert-->
                                <div class="alert alert-dismissible bg-light-primary d-flex flex-column flex-sm-row p-5 mb-10">
                                    <!--begin::Icon-->
                                    <i class="ki-duotone ki-notification-bing fs-2hx text-primary me-4 mb-5 mb-sm-0"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i>
                                    <!--end::Icon-->

                                    <!--begin::Wrapper-->
                                    <div class="d-flex flex-column pe-0 pe-sm-10">
                                        <!--begin::Title-->
                                        <h4 class="fw-semibold text-primary">Success</h4>
                                        <!--end::Title-->

                                        <!--begin::Content-->
                                        <span class="text-primary">{{ session()->get('success') }}</span>
                                        <!--end::Content-->
                                    </div>
                                    <!--end::Wrapper-->

                                    <!--begin::Close-->
                                    <button type="button" class="position-absolute position-sm-relative m-2 m-sm-0 top-0 end-0 btn btn-icon ms-sm-auto" data-bs-dismiss="alert">
                                        <i class="ki-duotone ki-cross fs-1 text-primary"><span class="path1"></span><span class="path2"></span></i>
                                    </button>
                                    <!--end::Close-->
                                </div>
                                <!--end::Alert-->
                                @elseif (session()->has('error'))
                                <!--begin::Alert-->
                                <div class="alert alert-dismissible bg-light-danger d-flex flex-column flex-sm-row p-5 mb-10">
                                    <!--begin::Icon-->
                                    <i class="ki-duotone ki-notification-bing fs-2hx text-danger me-4 mb-5 mb-sm-0"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i>
                                    <!--end::Icon-->

                                    <!--begin::Wrapper-->
                                    <div class="d-flex flex-column pe-0 pe-sm-10">
                                        <!--begin::Title-->
                                        <h4 class="fw-semibold text-danger">Fail</h4>
                                        <!--end::Title-->

                                        <!--begin::Content-->
                                        <span class="text-danger">{{ session()->get('error') }}</span>
                                        <!--end::Content-->
                                    </div>
                                    <!--end::Wrapper-->

                                    <!--begin::Close-->
                                    <button type="button" class="position-absolute position-sm-relative m-2 m-sm-0 top-0 end-0 btn btn-icon ms-sm-auto" data-bs-dismiss="alert">
                                        <i class="ki-duotone ki-cross fs-1 text-danger"><span class="path1"></span><span class="path2"></span></i>
                                    </button>
                                    <!--end::Close-->
                                </div>
                                <!--end::Alert-->
                                @endif
                                <form action="{{ route('transaction.store') }}" method="POST" enctype="multipart/form-data" id="form-create">
                                    @csrf
                                    <!--begin::Wrapper-->
                                    <div class="mb-0">
                                        <!--begin::Row-->
                                        <div class="row gx-10 mb-5">
                                            <!--begin::Col-->
                                            <div class="col-lg-12">
                                                <div class="form-group mb-5">
                                                    <label class="form-label fw-bold fs-6 text-gray-700">Type</label>
                                                    <select name="type" id="trx-type" data-control="select2" data-placeholder="Select type" class="form-select {{ $errors->get('type') ? 'is-invalid' : '' }}">
                                                        <option value=""></option>
                                                        <option value="top_up" {{ old('type') == 'top_up' ? 'selected' : '' }}>
                                                            Topup
                                                        </option>
                                                        <option value="transaksi" {{ old('type') == 'transaksi' ? 'selected' : '' }}>
                                                            Transaction
                                                        </option>
                                                    </select>
                                                    @if ($errors->get('type'))
                                                    <div class="invalid-feedback">{{ $errors->first('type') }}</div>
                                                    @endif
                                                </div>
                                                <div class="form-group mb-5">
                                                    <label class="form-label fs-6 fw-bold text-gray-700">Amount</label>
                                                    <input type="number" class="form-control text-end {{ $errors->get('amount') ? 'is-invalid' : '' }}" name="amount" value="{{ old('amount') }}" />
                                                    @if ($errors->get('amount'))
                                                    <div class="invalid-feedback">{{ $errors->first('amount') }}</div>
                                                    @endif
                                                </div>
                                                <div class="form-group mb-5">
                                                    <label class="form-label fs-6 fw-bold text-gray-700">Note</label>
                                                    <textarea name="note" class="form-control {{ $errors->get('note') ? 'is-invalid' : '' }}" rows="3">{{ old('note') }}</textarea>
                                                    @if ($errors->get('note'))
                                                    <div class="invalid-feedback">{{ $errors->first('note') }}</div>
                                                    @endif
                                                </div>
                                                <div class="form-group mb-5" id="evidence-group">
                                                    <label class="form-label fs-6 fw-bold text-gray-700">Payment Slip</label>
                                                    <input type="file" name="evidence" accept="image/*" class="form-control {{ $errors->get('evidence') ? 'is-invalid' : '' }}">
                                                    @if ($errors->get('evidence'))
                                                    <div class="invalid-feedback">{{ $errors->first('evidence') }}</div>
                                                    @endif
                                                </div>
                                                <button type="submit" class="btn btn-primary w-100" id="btn-submit">
                                                    <i class="ki-outline ki-triangle fs-3"></i>Create Transaction</button>
                                            </div>
                                            <!--end::Col-->
                                        </div>
                                        <!--end::Row-->
                                    </div>
                                    <!--end::Wrapper-->
                                </form>
                                <!--end::Form-->
                            </div>
                            <!--end::Card body-->
                        </div>
                        <!--end::Card-->
                    </div>
                    <!--end::Content-->
                    <!--begin::Sidebar-->
                    <div class="flex-lg-auto min-w-lg-400px">
                        <!--begin::Card-->
                        <div class="card" data-kt-sticky="true" data-kt-sticky-name="invoice" data-kt-sticky-offset="{default: false, lg: '200px'}" data-kt-sticky-width="{lg: '250px', lg: '300px'}" data-kt-sticky-left="auto" data-kt-sticky-top="150px" data-kt-sticky-animation="false" data-kt-sticky-zindex="95">
                            <!--begin::Card body-->
                            <div class="card-body p-10">
                                <div class="mb-4 px-9">
                                    <!--begin::Info-->
                                    <div class="d-flex align-items-center mb-2">
                                        <!--begin::Currency-->
                                        <span class="fs-4 fw-semibold text-gray-400 align-self-start me-1>">Rp</span>
                                        <!--end::Currency-->
                                        <!--begin::Value-->
                                        <span class="fs-2hx fw-bold text-gray-800 me-2 lh-1">{{ number_format($user->balance, 2, ',', '.') }}</span>
                                        <!--end::Value-->
                                    </div>
                                    <!--end::Info-->
                                    <!--begin::Description-->
                                    <span class="fs-6 fw-semibold text-gray-400">Balance</span>
                                    <!--end::Description-->
                                </div>
                            </div>
                            <!--end::Card body-->
                        </div>
                        <!--end::Card-->
                    </div>
                    <!--end::Sidebar-->
                </div>
                <!--end::Layout-->
            </div>
            <!--end::Content container-->
        </div>
        <!--end::Content-->
    </div>
    @push('scripts')
    <script src="{{ asset('assets/js/custom/apps/invoices/create.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#evidence-group').hide();
        });
        $('#trx-type').on('change', function() {
            if ($(this).val() == 'top_up') {
                $('#evidence-group').show();
            } else {
                $('#evidence-group').hide();
            }
        });
        $('#form-create').on('submit', function(e) {
            $('#btn-submit').prop('disabled', true);
        });
    </script>
    @endpush
</x-default-layout>

resources/views/pages/transaction/index.blade.php
<x-default-layout>
    <div class="d-flex flex-column flex-column-fluid">
        <!--begin::Toolbar-->
        <div id="kt_app_toolbar" class="app-toolbar pt-7 pt-lg-10">
            <!--begin::Toolbar container-->
            <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex align-items-stretch">
                <!--begin::Toolbar wrapper-->
                <div class="app-toolbar-wrapper d-flex flex-stack flex-wrap gap-4 w-100">
                    <!--begin::Page title-->
                    <div class="page-title d-flex flex-column justify-content-center gap-1 me-3">
                        <!--begin::Title-->
                        <h1 class="page-heading d-flex flex-column justify-content-center text-dark fw-bold fs-3 m-0">Balance History</h1>
                        <!--end::Title-->
                    </div>
                    <!--end::Page title-->
                    <div class="d-flex align-items-center gap-2 gap-lg-3">
                        <a href="{{ route('transaction.create') }}" class="btn btn-flex btn-primary h-40px fs-7 fw-bold">Create Transaction</a>
                    </div>
                </div>
                <!--end::Toolbar wrapper-->
            </div>
            <!--end::Toolbar container-->
        </div>
        <!--end::Toolbar-->
        <!--begin::Content-->
        <div id="kt_app_content" class="app-content flex-column-fluid">
            <!--begin::Content container-->
            <div id="kt_app_content_container" class="app-container container-fluid">
                <!--begin::Layout-->
                <div class="d-flex flex-column flex-lg-row">
                    <div class="card" data-kt-sticky="true" data-kt-sticky-name="invoice" data-kt-sticky-offset="{default: false, lg: '200px'}" data-kt-sticky-width="{lg: '250px', lg: '300px'}" data-kt-sticky-left="auto" data-kt-sticky-top="150px" data-kt-sticky-animation="false" data-kt-sticky-zindex="95">
                        <!--begin::Card body-->
                        <div class="card-body p-10">
                            <div class="mb-4 px-9">
                                <!--begin::Info-->
                                <div class="d-flex align-items-center mb-2">
                                    <!--begin::Currency-->
                                    <span class="fs-4 fw-semibold text-gray-400 align-self-start me-1>">Rp</span>
                                    <!--end::Currency-->
                                    <!--begin::Value-->
                                    <span class="fs-2hx fw-bold text-gray-800 me-2 lh-1">{{ number_format($user->balance, 2, ',', '.') }}</span>
                                    <!--end::Value-->
                                </div>
                                <!--end::Info-->
                                <!--begin::Description-->
                                <span class="fs-6 fw-semibold text-gray-400">Balance</span>
                                <!--end::Description-->
                            </div>
                        </div>
                        <!--end::Card body-->
                    </div>
                </div>
                <div class="d-flex flex-column flex-lg-row">
                    <!--begin::Content-->
                    <div class="flex-lg-row-fluid mb-10 mb-lg-0 me-lg-7 me-xl-10">
                        <!--begin::Card-->
                        <div class="card">
                            <!--begin::Card body-->
                            <div class="card-body p-12 table-responsive">
                                <table id="table-history" class="table">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Code</th>
                                            <th>Type</th>
                                            <th>Amount</th>
                                            <th>Note</th>
                                            <th>Payment Slip</th>
                                            <th>Created Date</th>
                                        </tr>
                                    </thead>
                                    <tbody class="text-gray-600 fw-semibold">
                                    </tbody>
                                </table>
                            </div>
                            <!--end::Card body-->
                        </div>
                        <!--end::Card-->
                    </div>
                    <!--end::Content-->
                </div>
                <!--end::Layout-->
            </div>
            <!--end::Content container-->
        </div>
        <!--end::Content-->
    </div>
    @push('scripts')
    <script>
        $(document).ready(function() {
            var table = $('#table-history').DataTable({
                ajax: "{{ route('transaction.index') }}",
                processing: true,
                serverSide: true,
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        orderable: false,
                        searchable: false,
                    },
                    {
                        data: 'code',
                        name: 'code'
                    },
                    {
                        data: 'type',
                        name: 'type',
                        render: function(data) {
                            if (data == 'top_up') {
                                return `<span class="badge badge-light-success fs-base">Topup</span>`
                            }
                            return `<span class="badge badge-light-danger fs-base">Transaction</span>`
                        }
                    },
                    {
                        data: 'amount',
                        name: 'amount '
                    },
                    {
                        data: 'note',
                        name: 'note'
                    },
                    {
                        data: 'evidence',
                        name: 'evidence',
                        orderable: false,
                        searchable: false,
                        render: function(data) {
                            if (data == null) {
                                return `-`
                            }
                            return `<a href="{{ url('') }}/storage/${data}" target="_blank">Download</a>`
                        }
                    },
                    {
                        data: 'created_at',
                        name: 'created_at'
                    },
                ],
                order: [
                    [6, 'desc']
                ]
            });
        });
    </script>
    @endpush
</x-default-layout>